- name: Remove Existing dotfiles Repository
  file:
    state: absent
    path: "{{ ansible_env.HOME }}/dotfiles"

- name: Pull dotfiles Repository
  git:
    repo: "https://github.com/{{ dotfiles_repository }}.git"
    dest: "{{ ansible_env.HOME }}/dotfiles"
    force: yes
    depth: 3

- name: Update dotfiles Repository Remote URL
  command: "git remote set-url origin git@github.com:{{ dotfiles_repository }}.git"
  args:
    chdir: "{{ ansible_env.HOME }}/dotfiles"

- name: Create ~/Library/Application Support/iTerm2/DynamicProfiles Directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles/"

- name: Link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { src: "{{ ansible_env.HOME }}/dotfiles/.zshrc", dest: "{{ ansible_env.HOME }}/.zshrc" }
    - { src: "{{ ansible_env.HOME }}/dotfiles/.gitconfig", dest: "{{ ansible_env.HOME }}/.gitconfig"}
    - { src: "{{ ansible_env.HOME }}/dotfiles/.gitrc", dest: "{{ ansible_env.HOME }}/.gitrc" }

- name: Source dotfiles in .zshrc
  lineinfile:
    dest: ~/.zshrc
    regexp: "{{ item }}"
    line: "source $HOME/{{ item }}"
    state: present
  with_items:
    - '.gitrc'

- name: Setup dotfiles Sync
  include: dotfiles-sync.yml